"""Turn GPU-lab result files into results/BENCHMARKS.md (Phase 6).

    uv run python -m bench.report results/raw/<run>/fxassist_results  [--out results/BENCHMARKS.md]

Rules (ADR-017, rule 2 of the build contract):
  - numbers come only from the result files; anything not measured is written as PENDING
  - each table cell is the median of the repetitions, with the min-max spread (BEN-03)
  - p50 and p95, error rate shown separately (BEN-05, BEN-06)
  - files from a mock dry run are labelled as such and must never be committed as results
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from .matrix import EXPERIMENTS

PENDING = "PENDING"


def load_rows(results: Path) -> list[dict[str, Any]]:
    path = results / "benchmark.jsonl"
    if not path.exists():
        return []
    rows = []
    for line in path.read_text().splitlines():
        try:
            rows.append(json.loads(line))
        except ValueError:
            continue  # a row cut off by a killed session
    return rows


def median_spread(values: list[float | None], fmt: str = "{:.2f}") -> str:
    vals = [v for v in values if v is not None]
    if not vals:
        return PENDING
    med = statistics.median(vals)
    if len(vals) == 1:
        return fmt.format(med) + " (1 rep)"
    return f"{fmt.format(med)} ({fmt.format(min(vals))}-{fmt.format(max(vals))})"


# vLLM 0.31.0 log formats (read from its source: v1/worker/gpu/model_runner.py,
# v1/worker/gpu_worker.py, v1/core/kv_cache_utils.py).
_LOG_PATTERNS = {
    "model_gib": re.compile(r"Model loading took ([\d.]+) GiB memory and ([\d.]+) seconds"),
    "kv_gib": re.compile(r"Available KV cache memory: ([\d.]+) GiB"),
    "kv_tokens": re.compile(r"KV cache size: ([\d,]+) tokens"),
    "max_concurrency": re.compile(
        r"Maximum concurrency for ([\d,]+) tokens per request: ([\d.]+)x"
    ),
}


def memory_from_log(text: str) -> dict[str, str]:
    found = {k: PENDING for k in ("model_gib", "load_s", "kv_gib", "kv_tokens", "max_concurrency")}
    if m := _LOG_PATTERNS["model_gib"].findall(text):
        found["model_gib"], found["load_s"] = m[-1][0], f"{float(m[-1][1]):.1f}"
    if m := _LOG_PATTERNS["kv_gib"].findall(text):
        found["kv_gib"] = m[-1]
    if m := _LOG_PATTERNS["kv_tokens"].findall(text):
        found["kv_tokens"] = m[-1]
    if m := _LOG_PATTERNS["max_concurrency"].findall(text):
        found["max_concurrency"] = f"{m[-1][1]}x at {m[-1][0]} tokens"
    return found


def stage(results: Path, name: str) -> dict[str, Any]:
    """The last record of a stage in stages.jsonl, or {}."""
    path = results / "stages.jsonl"
    found: dict[str, Any] = {}
    for line in path.read_text().splitlines() if path.exists() else []:
        row = json.loads(line)
        if row.get("stage") == name:
            found = row
    return found


def by_cell(rows: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    cells: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        cells[r["cell_key"]].append(r)
    return cells


def cell_line(reps: list[dict[str, Any]] | None, label: str) -> str:
    if not reps:
        return f"| {label} | " + " | ".join([PENDING] * 6) + " |"
    get = lambda k: [r.get(k) for r in reps]  # noqa: E731
    return (
        f"| {label} | {median_spread(get('ttft_p50_s'))} | {median_spread(get('ttft_p95_s'))} | "
        f"{median_spread(get('latency_p50_s'))} | {median_spread(get('latency_p95_s'))} | "
        f"{median_spread(get('throughput_tokens_per_s'), '{:.0f}')} | "
        f"{median_spread(get('error_rate'), '{:.1%}')} |"
    )


HEADER = (
    "| Cell | TTFT p50 (s) | TTFT p95 (s) | Latency p50 (s) | Latency p95 (s) | "
    "Throughput (tokens/s) | Error rate |\n|---|---|---|---|---|---|---|"
)


def render(results: Path) -> str:
    rows = load_rows(results)
    cells = by_cell(rows)
    env = (
        json.loads((results / "environment.json").read_text())
        if (results / "environment.json").exists()
        else {}
    )
    smoke = (
        json.loads((results / "smoke.json").read_text())
        if (results / "smoke.json").exists()
        else {}
    )
    mock = env.get("mode") == "mock"
    out = ["# Benchmarks", ""]
    if mock:
        out += [
            "> **MOCK DRY RUN: these numbers come from the mock LLM, not a GPU. Not results; "
            "never commit this file as results/BENCHMARKS.md.**",
            "",
        ]
    out += [
        "Generated by `bench/report.py` from the GPU-lab result files. Method: "
        "[docs/BENCHMARK_METHOD.md](../docs/BENCHMARK_METHOD.md). Each cell: median of the "
        "repetitions, with the min-max range in brackets. Throughput counts generated tokens "
        "per second across all concurrent requests. T4 numbers are not comparable to A100/H100 "
        "numbers (ADR-017).",
        "",
        "## Setup",
        "",
        f"- GPUs: {', '.join(g['name'] for g in env.get('gpus', [])) or PENDING}",
        f"- vLLM, PyTorch, CUDA: {stage(results, 'install-vllm').get('versions', PENDING)}",
        f"- Attention backend: {smoke.get('backend', PENDING)} (log says: "
        f"{(smoke.get('backend_seen_in_log') or [PENDING])[0]})",
        f"- `ignore_eos` gives exact output length: {smoke.get('ignore_eos_exact', PENDING)}",
        "- Prompt sets (SHA-256): "
        + ", ".join(
            sorted({f"{r['prompt_set']} `{r['prompt_set_sha256'][:12]}`" for r in rows})
            or [PENDING]
        ),
        "",
    ]
    baseline = {e.variant: e for e in EXPERIMENTS if e.name == "baseline"}
    out += ["## FP16 vs AWQ (BEN-09)", "", HEADER]
    for variant in ("fp16", "awq"):
        for c in baseline[variant].cells:
            out.append(cell_line(cells.get(c.key), f"{variant}, c={c.concurrency}, {c.prompt_set}"))
    out += [
        "",
        "## Knobs, one at a time (BEN-07), against the FP16 baseline at concurrency 16",
        "",
        HEADER,
    ]
    for e in EXPERIMENTS:
        if e.name == "baseline" or e.server.get("tensor_parallel_size"):
            continue
        for c in e.cells:
            base_key = f"baseline|fp16|c{c.concurrency}|{c.prompt_set}"
            out.append(cell_line(cells.get(base_key), f"baseline, {c.prompt_set}"))
            out.append(cell_line(cells.get(c.key), f"{e.name} ({e.server}), {c.prompt_set}"))
    out += ["", "## Tensor parallel: 2 GPUs vs 1 (Phase 7)", "", HEADER]
    for e in EXPERIMENTS:
        if e.server.get("tensor_parallel_size"):
            for c in e.cells:
                out.append(
                    cell_line(
                        cells.get(f"baseline|fp16|c{c.concurrency}|{c.prompt_set}"),
                        f"TP=1, c={c.concurrency}, {c.prompt_set}",
                    )
                )
                out.append(cell_line(cells.get(c.key), f"TP=2, c={c.concurrency}, {c.prompt_set}"))
    out += [
        "",
        "## GPU memory per server start (from vLLM's own log lines, GPU-03)",
        "",
        "| Server | Model memory (GiB) | Load time (s) | KV cache memory (GiB) | KV cache (tokens) "
        "| Max concurrency at max length |",
        "|---|---|---|---|---|---|",
    ]
    logs = (
        sorted((results / "server-logs").glob("*.log"))
        if (results / "server-logs").exists()
        else []
    )
    for log in logs:
        m = memory_from_log(log.read_text(errors="replace"))
        out.append(
            f"| {log.stem} | {m['model_gib']} | {m['load_s']} | {m['kv_gib']} | {m['kv_tokens']} | {m['max_concurrency']} |"
        )
    if not logs:
        out.append(f"| {PENDING} | | | | | |")
    out += ["", "## Experiment log", "", "| Stage | Status | Note |", "|---|---|---|"]
    stages = results / "stages.jsonl"
    for line in stages.read_text().splitlines() if stages.exists() else []:
        s = json.loads(line)
        note = str(s.get("note", "")).replace("\n", " ").replace("|", "/")[:160]
        out.append(f"| {s['stage']} | {s['status']} | {note} |")
    if not stages.exists():
        out.append(f"| {PENDING} | | |")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "results", type=Path, help="directory with benchmark.jsonl, stages.jsonl ..."
    )
    parser.add_argument("--out", type=Path, default=Path("results/BENCHMARKS.md"))
    args = parser.parse_args()
    text = render(args.results)
    if "MOCK DRY RUN" in text and args.out == Path("results/BENCHMARKS.md"):
        print(
            "refusing to write mock numbers to results/BENCHMARKS.md; pass --out elsewhere",
            file=sys.stderr,
        )
        return 2
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
